//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEA.Repository.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblArea()
        {
            this.tblSubAreas = new HashSet<tblSubArea>();
        }
    
        public decimal AreaID { get; set; }
        public string Areaname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubArea> tblSubAreas { get; set; }
    }
}
