//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEA.Repository.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public decimal ContactsID { get; set; }
        public decimal Emp_ID { get; set; }
        public string Type { get; set; }
        public string Subtype { get; set; }
        public byte ContactNo { get; set; }
        public decimal RelationID { get; set; }
        public bool IsinActive { get; set; }
        public System.DateTime LastChangedAt { get; set; }
    }
}
