//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEA.Repository.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        public decimal Location_ID { get; set; }
        public decimal Emp_ID { get; set; }
        public string type { get; set; }
        public decimal CountryID { get; set; }
        public decimal StateID { get; set; }
        public decimal CityID { get; set; }
        public decimal AreaID { get; set; }
        public decimal SubareaID { get; set; }
        public string Line1_address { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastChangedAt { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual tblCountry tblCountry { get; set; }
    }
}
