//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEA.Repository.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRelation
    {
        public decimal RelationID { get; set; }
        public string Relation { get; set; }
        public string Description { get; set; }
        public System.DateTime LastChangedAt { get; set; }
    }
}
