//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEA.Repository.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubArea
    {
        public decimal SubAreaID { get; set; }
        public decimal AreaID { get; set; }
        public string SubAreaName { get; set; }
    
        public virtual tblArea tblArea { get; set; }
    }
}
