//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPITEA.Repository.ModelEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserCredential
    {
        public decimal Id { get; set; }
        public string Username { get; set; }
        public string EmailId { get; set; }
        public string PasswordHash { get; set; }
        public bool IsApproved { get; set; }
        public decimal EmployeeId { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
